### ISSUE TITLE
Tạo giao diện trang chủ cơ bản

### ISSUE THREAD

**Issue by go-buster** [go-buster/LinuxFinalEx#3]
Thêm các phần placeholder cho các phần chính trên trang chủ.

**Comment by huynv22kit** [comment]
Làm giao diện theo như ý tưởng ban đầu

**Comment by go-buster** [comment]
> Làm giao diện theo như ý tưởng ban đầu

Được rồi sẽ làm theo như ý tưởng giao diện ban đầu
